## library() calls go here
library(conflicted)
library(coda)
library(dotenv)
library(targets)
library(tarchetypes)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(lubridate)
library(stringr)
library(quarto)
library(DHARMa)
library(greta)
library(fs)
library(glue)
library(colorspace)

conflicts_prefer(greta::`%*%`)
conflicts_prefer(greta::poisson)
conflicts_prefer(dplyr::filter)
conflicts_prefer(greta::apply)
